name: Deploy to Minikube using GitHub Actions

on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest
    name: Build Node.js Docker image and deploy to Minikube
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Start Minikube
        uses: medyagh/setup-minikube@master

      - name: Check cluster
        run: kubectl get pods -A

      - name: Build image
        run: |
          export SHELL=/bin/bash
          eval $(minikube -p minikube docker-env)
          docker build -f ./Dockerfile -t devopshint/node-app:latest .
          docker images

      - name: Deploy to Minikube
        run: kubectl apply -f k8s-node-app.yaml

      - name: Wait for nodejs-app pod
        run: |
          kubectl wait --for=condition=ready pod -l app=nodejs-app -n default --timeout=180s

      - name: Test service URLs
        run: |
          minikube service list
          minikube service nodejs-app --url
